/**
 * Defines the request payload for the Ollama `/api/generate` endpoint.
 * @example
 * ```typescript
 * const req: OllamaGenerateRequest = { model: 'gemma3:270m', prompt: 'Hello world' };
 * ```
 */
export interface OllamaGenerateRequest {
	/** The name of the model to use for generation, e.g., 'gemma3:270m'. */
	model: string;
	/** The prompt to be sent to the language model. */
	prompt: string;
}

/**
 * Defines the structure of the response from the Ollama `/api/generate` endpoint.
 * @example
 * ```typescript
 * const res: OllamaGenerateResponse = { response: 'Hello world!' };
 * ```
 */
export interface OllamaGenerateResponse {
	/** The text generated by the language model. */
	response: string;
}

/**
 * Represents a single message in a chat conversation for the Ollama chat API.
 * @example
 * ```typescript
 * const msg: OllamaChatMessage = { role: 'user', content: 'Hi!' };
 * ```
 */
export interface OllamaChatMessage {
	/** The role of the message sender, which can be 'user', 'assistant', or 'system'. */
	role: "user" | "assistant" | "system";
	/** The content of the message. */
	content: string;
}

/**
 * Defines the request payload for the Ollama `/api/chat` endpoint.
 * @example
 * ```typescript
 * const req: OllamaChatRequest = { model: 'gemma3:270m', messages: [ ... ] };
 * ```
 */
export interface OllamaChatRequest {
	/** The name of the model to use for the chat. */
	model: string;
	/** An array of `OllamaChatMessage` objects representing the conversation history. */
	messages: OllamaChatMessage[];
}

/**
 * Defines the structure of the response from the Ollama `/api/chat` endpoint.
 * @example
 * ```typescript
 * const res: OllamaChatResponse = { message: { role: 'assistant', content: 'Hello!' } };
 * ```
 */
export interface OllamaChatResponse {
	/** The message returned by the assistant. */
	message: OllamaChatMessage;
}

/**
 * Provides a type-safe client for interacting with a local Ollama server,
 * supporting both single-shot text generation and multi-turn chat sessions.
 *
 * @example
 * ```typescript
 * const client = new OllamaClient();
 * const text = await client.generate('Hello world');
 * const chatResponse = await client.chat([{ role: 'user', content: 'Hi!' }]);
 * ```
 */
export class OllamaClient {
	private model: string;
	private baseUrl: string;

	/**
	 * Creates a new instance of the `OllamaClient`.
	 * @param options - Optional configuration for the client, including the model name and base URL.
	 * @example
	 * ```typescript
	 * const client = new OllamaClient({ model: 'gemma3:270m', baseUrl: 'http://localhost:11434' });
	 * ```
	 */
	constructor(options?: { model?: string; baseUrl?: string }) {
		this.model = options?.model ?? "gemma3:270m";
		this.baseUrl = options?.baseUrl ?? "http://localhost:11434";
	}

	/**
	 * Checks if the Ollama server is reachable and responsive.
	 * @returns A `Promise` that resolves to `true` if the server is healthy, otherwise `false`.
	 * @example
	 * ```typescript
	 * const isHealthy = await client.healthCheck();
	 * ```
	 */
	async healthCheck(): Promise<boolean> {
		try {
			const res = await fetch(`${this.baseUrl}/api/tags`, { method: "GET" });
			return res.ok;
		} catch {
			return false;
		}
	}

	/**
	 * Generates text from a given prompt using the Ollama `/api/generate` endpoint.
	 * This method handles the streaming JSON response from Ollama and concatenates it.
	 * @param prompt - The prompt to send to the language model.
	 * @returns A `Promise` that resolves to the generated text.
	 * @example
	 * ```typescript
	 * const text = await client.generate('Tell me a joke.');
	 * ```
	 */
	async generate(prompt: string): Promise<string> {
		if (!(await this.healthCheck())) {
			throw new Error(`Ollama server not reachable at ${this.baseUrl}`);
		}
		const payload: OllamaGenerateRequest = { model: this.model, prompt };
		try {
			const res = await fetch(`${this.baseUrl}/api/generate`, {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify(payload),
			});
			if (!res.ok) throw new Error(`Ollama generate failed: ${res.status}`);
			const raw = await res.text();
			// Ollama streams JSON objects, one per line
			const lines = raw.split(/\r?\n/).filter(Boolean);
			let output = "";
			for (const line of lines) {
				try {
					const obj = JSON.parse(line);
					if (typeof obj.response === "string") {
						output += obj.response;
					}
				} catch (jsonErr) {
					console.error("Failed to parse line as JSON:", line);
				}
			}
			if (!output) {
				throw new Error("No valid response found in Ollama generate output");
			}
			return output;
		} catch (err) {
			throw new Error(`OllamaClient.generate error: ${err}`);
		}
	}

	/**
	 * Sends a multi-turn chat conversation to the Ollama `/api/chat` endpoint.
	 * This method handles the streaming JSON response and concatenates the content.
	 * @param messages - An array of `OllamaChatMessage` objects representing the conversation.
	 * @returns A `Promise` that resolves to the assistant's complete response as a string.
	 * @example
	 * ```typescript
	 * const response = await client.chat([{ role: 'user', content: 'What is the capital of France?' }]);
	 * ```
	 */
	async chat(messages: OllamaChatMessage[]): Promise<string> {
		if (!(await this.healthCheck())) {
			throw new Error(`Ollama server not reachable at ${this.baseUrl}`);
		}
		const payload: OllamaChatRequest = { model: this.model, messages };
		try {
			const res = await fetch(`${this.baseUrl}/api/chat`, {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify(payload),
			});
			if (!res.ok) throw new Error(`Ollama chat failed: ${res.status}`);
			const raw = await res.text();
			// Ollama streams JSON objects, one per line
			const lines = raw.split(/\r?\n/).filter(Boolean);
			let output = "";
			for (const line of lines) {
				try {
					const obj = JSON.parse(line);
					if (obj.message && typeof obj.message.content === "string") {
						output += obj.message.content;
					}
				} catch (jsonErr) {
					console.error("Failed to parse line as JSON:", line);
				}
			}
			if (!output) {
				throw new Error(
					"No valid message content found in Ollama chat response",
				);
			}
			return output;
		} catch (err) {
			throw new Error(`OllamaClient.chat error: ${err}`);
		}
	}
}
